[package]
name = "systest"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[dependencies]
miniz-sys = { path = '../miniz-sys' }
libc = "0.2"

[build-dependencies]
ctest = { git = 'https://github.com/alexcrichton/ctest', branch = 'use-maybe-unini' }
